runtime: nodejs16

env_variables:
  PORT: 3600
  HOST: localhost
  NODE_ENV: development
  APP_KEY: TMKRelGUHFeE0lpIocNzCN7lcCuIKDE7
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_USER: root
  DB_PASSWORD:
  DB_NAME: gestagio
