runtime: nodejs16

env_variables:
  PORT: 3333
  HOST: 127.0.0.1
  NODE_ENV: production
  APP_KEY: TMKRelGUHFeE0lpIocNzCN7lcCuIKDE7
  DB_CONNECTION: mysql
  DB_HOST: sql572.main-hosting.eu
  DB_USER: u813647343_root
  DB_PASSWORD: Dtna##38*
  DB_NAME: u813647343_gestagio
